import type { SourceConfig } from "./types";

// ===== 股市 RSS 源 =====
const STOCK_SOURCES: SourceConfig[] = [
  // ===== A股 / 中文 =====
  {
    id: "xueqiu",
    name: "雪球",
    url: "https://xueqiu.com/rss",
    type: "rss",
    category: "cn",
    icon: "📊",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: false,
    hotness: "niche",
    description: "⚠️ RSS已失效（ECONNRESET），待修复",
  },
  {
    id: "cls-cn",
    name: "华尔街见闻",
    url: "https://wallstreetcn.com/feed",
    type: "rss",
    category: "cn",
    icon: "📈",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: false,
    description: "⚠️ RSS已失效，待修复",
  },
  {
    id: "caixin",
    name: "财新网",
    url: "https://www.caixin.com/rss/",
    type: "rss",
    category: "cn",
    icon: "📰",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: false,
    hotness: "quality",
    description: "专业财经媒体，深度调查报道权威",
  },
  {
    id: "yicai",
    name: "第一财经",
    url: "https://www.yicai.com/feed",
    type: "rss",
    category: "cn",
    icon: "🏦",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: false,
    hotness: "quality",
    description: "主流财经媒体，覆盖宏观和市场资讯",
  },
  {
    id: "eastmoney",
    name: "东方财富",
    url: "https://finance.eastmoney.com/rss/",
    type: "rss",
    category: "cn",
    icon: "💹",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: false,
    hotness: "hot",
    description: "A股最大财经门户，行情资讯全覆盖",
  },
  {
    id: "fin-zh",
    name: "新浪财经",
    url: "https://rss.finance.sina.com.cn/rss/",
    type: "rss",
    category: "cn",
    icon: "📱",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: false,
    hotness: "hot",
    description: "老牌财经门户，覆盖面广更新快",
  },
  // ===== 美股 / 国际 =====
  {
    id: "ft-china",
    name: "FT中文网",
    url: "https://www.ftchinese.com/rss/feed",
    type: "rss",
    category: "us",
    icon: "📰",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "reuters",
    name: "Reuters",
    url: "https://www.reutersagency.com/feed/",
    type: "rss",
    category: "us",
    icon: "🏛",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
    hotness: "quality",
    description: "全球顶级财经通讯社，时效性第一",
  },
  {
    id: "investing",
    name: "Investing.com",
    url: "https://www.investing.com/rss/news.rss",
    type: "rss",
    category: "us",
    icon: "🌍",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "seekingalpha",
    name: "Seeking Alpha",
    url: "https://seekingalpha.com/feed.xml",
    type: "rss",
    category: "us",
    icon: "🏛",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/rssindex",
    type: "rss",
    category: "us",
    icon: "💹",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "wsj",
    name: "WSJ",
    url: "https://www.wsj.com/xml/rss/3_7085.xml",
    type: "rss",
    category: "us",
    icon: "📊",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "bloomberg",
    name: "Bloomberg",
    url: "https://feeds.bloomberg.com/markets/news.rss",
    type: "rss",
    category: "us",
    icon: "🏛",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "cnbc",
    name: "CNBC",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    type: "rss",
    category: "us",
    icon: "📺",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
];

// ===== 币圈 RSS 源 =====
const CRYPTO_SOURCES: SourceConfig[] = [
  {
    id: "coindesk",
    name: "CoinDesk",
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    type: "rss",
    category: "crypto",
    icon: "📰",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "cointelegraph",
    name: "Cointelegraph",
    url: "https://cointelegraph.com/rss",
    type: "rss",
    category: "crypto",
    icon: "⚡",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "theblock",
    name: "The Block",
    url: "https://www.theblock.co/rss",
    type: "rss",
    category: "crypto",
    icon: "📊",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: false,
    description: "⚠️ RSS已失效（404），待修复",
  },
  {
    id: "decrypt",
    name: "Decrypt",
    url: "https://decrypt.co/feed",
    type: "rss",
    category: "crypto",
    icon: "🔐",
    lang: "en",
    tier: 2,
    interval: 60,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "bitcoinmagazine",
    name: "Bitcoin Magazine",
    url: "https://bitcoinmagazine.com/rss",
    type: "rss",
    category: "crypto",
    icon: "₿",
    lang: "en",
    tier: 2,
    interval: 60,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "blockworks",
    name: "Blockworks",
    url: "https://blockworks.co/feed",
    type: "rss",
    category: "crypto",
    icon: "🏦",
    lang: "en",
    tier: 2,
    interval: 60,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "cryptoslate",
    name: "CryptoSlate",
    url: "https://cryptoslate.com/feed/",
    type: "rss",
    category: "crypto",
    icon: "📡",
    lang: "en",
    tier: 2,
    interval: 60,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
];

export const SOURCES: SourceConfig[] = [
  // ===== Tier 1 =====
  {
    id: "tmtpost",
    name: "钛媒体",
    url: "https://www.tmtpost.com/rss",
    type: "rss",
    category: "ai",
    icon: "🔬",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
    description: "深度商业科技媒体，替代机器之心（原RSS已失效）",
  },
  {
    id: "qbitai",
    name: "量子位",
    url: "https://www.qbitai.com/feed",
    type: "rss",
    category: "ai",
    icon: "🔬",
    lang: "zh",
    tier: 1,
    interval: 15,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "mit-tech-review",
    name: "MIT Tech Review",
    url: "https://www.technologyreview.com/feed/",
    type: "rss",
    category: "ai",
    icon: "📐",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    url: "https://huggingface.co/blog/feed.xml",
    type: "rss",
    category: "ai",
    icon: "🤗",
    lang: "en",
    tier: 1,
    interval: 120,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "anthropic",
    name: "Anthropic",
    url: "https://anthropic.com/blog/rss",
    type: "rss",
    category: "ai",
    icon: "🤖",
    lang: "en",
    tier: 1,
    interval: 60,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "openai",
    name: "OpenAI",
    url: "https://openai.com/blog/rss",
    type: "rss",
    category: "ai",
    icon: "🧠",
    lang: "en",
    tier: 1,
    interval: 60,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "36kr",
    name: "36氪",
    url: "https://36kr.com/feed",
    type: "rss",
    category: "tech",
    icon: "📡",
    lang: "zh",
    tier: 1,
    interval: 15,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    type: "rss",
    category: "tech",
    icon: "🌐",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    url: "https://news.ycombinator.com/rss",
    type: "rss",
    category: "tech",
    icon: "💬",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "ruanyifeng",
    name: "阮一峰",
    url: "https://www.ruanyifeng.com/blog/atom.xml",
    type: "rss",
    category: "tech",
    icon: "📚",
    lang: "zh",
    tier: 1,
    interval: 1440,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "simon-willison",
    name: "Simon Willison",
    url: "https://simonwillison.net/atom/everything/",
    type: "rss",
    category: "ai",
    icon: "✍️",
    lang: "en",
    tier: 1,
    interval: 120,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },

  // ===== Tier 2 =====
  {
    id: "ifanr",
    name: "爱范儿",
    url: "https://www.ifanr.com/feed",
    type: "rss",
    category: "tech",
    icon: "📱",
    lang: "zh",
    tier: 2,
    interval: 120,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "ithome",
    name: "IT之家",
    url: "https://www.ithome.com/rss",
    type: "rss",
    category: "tech",
    icon: "💻",
    lang: "zh",
    tier: 2,
    interval: 60,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "sspai",
    name: "少数派",
    url: "https://sspai.com/feed",
    type: "rss",
    category: "tech",
    icon: "✍️",
    lang: "zh",
    tier: 2,
    interval: 240,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "venturebeat",
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    type: "rss",
    category: "ai",
    icon: "📈",
    lang: "en",
    tier: 2,
    interval: 120,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "ars-technica",
    name: "Ars Technica AI",
    url: "https://arstechnica.com/ai/feed/",
    type: "rss",
    category: "tech",
    icon: "⚙️",
    lang: "en",
    tier: 2,
    interval: 240,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "deepmind",
    name: "DeepMind",
    url: "https://deepmind.google/blog/rss/",
    type: "rss",
    category: "ai",
    icon: "🧪",
    lang: "en",
    tier: 2,
    interval: 480,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "36kr-funding",
    name: "36氪创投",
    url: "https://36kr.com/motif/feed/117",
    type: "rss",
    category: "funding",
    icon: "💰",
    lang: "zh",
    tier: 2,
    interval: 120,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "crunchbase",
    name: "Crunchbase News",
    url: "http://news.crunchbase.com/feed/",
    type: "rss",
    category: "funding",
    icon: "💰",
    lang: "en",
    tier: 2,
    interval: 240,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  // ===== 新增推荐源 =====
  {
    id: "one-useful-thing",
    name: "One Useful Thing",
    url: "https://oneusefulthing.substack.com/feed",
    type: "rss",
    category: "ai",
    icon: "🎓",
    lang: "en",
    tier: 2,
    interval: 480,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
    description: "Prof. Ethan Mollick 的 AI 实战博客",
  },
  {
    id: "latent-space",
    name: "Latent Space",
    url: "https://www.latent.space/feed",
    type: "rss",
    category: "ai",
    icon: "🔧",
    lang: "en",
    tier: 2,
    interval: 480,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
    description: "AI 工程实践和技术深度",
  },
  {
    id: "geekpark",
    name: "极客公园",
    url: "https://rsshub.app/geekpark/breakingnews",
    type: "rsshub",
    category: "tech",
    icon: "🎯",
    lang: "zh",
    tier: 2,
    interval: 120,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
    description: "科技人物访谈和深度报道",
  },
  {
    id: "product-hunt",
    name: "Product Hunt",
    url: "https://www.producthunt.com/feed",
    type: "rss",
    category: "tech",
    icon: "🚀",
    lang: "en",
    tier: 3,
    interval: 240,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
    description: "全球新产品发布平台",
  },
  {
    id: "github-trending",
    name: "GitHub Trending",
    url: "https://rsshub.app/github/trending/daily",
    type: "rsshub",
    category: "tech",
    icon: "📦",
    lang: "en",
    tier: 3,
    interval: 240,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
    description: "开源项目热度风向标",
  },
  {
    id: "v2ex-hot",
    name: "V2EX 最热",
    url: "https://www.v2ex.com/index.xml",
    type: "rss",
    category: "tech",
    icon: "💬",
    lang: "zh",
    tier: 3,
    interval: 120,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
    description: "中文技术社区讨论热点",
  },
  {
    id: "howie-weekly",
    name: "老胡的信息周刊",
    url: "https://weekly.howie6879.com/rss/rss.xml",
    type: "rss",
    category: "tech",
    icon: "📰",
    lang: "zh",
    tier: 3,
    interval: 1440,
    aiTranslate: false,
    aiPriority: "low",
    active: true,
    description: "精选技术文章和信息汇总",
  },
  {
    id: "hello-github",
    name: "HelloGitHub",
    url: "https://hellogithub.com/rss",
    type: "rss",
    category: "tech",
    icon: "⭐",
    lang: "zh",
    tier: 3,
    interval: 1440,
    aiTranslate: false,
    aiPriority: "low",
    active: true,
    description: "开源项目推荐月刊",
  },
  {
    id: "aigc-weekly",
    name: "AIGC Weekly",
    url: "https://quail.ink/op7418/feed/atom",
    type: "rss",
    category: "ai",
    icon: "✨",
    lang: "zh",
    tier: 3,
    interval: 1440,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
    description: "AIGC 领域每周精选",
  },
  {
    id: "arxiv-ai",
    name: "arXiv AI",
    url: "https://rsshub.app/arxiv/quant-ph",
    type: "rsshub",
    category: "ai",
    icon: "📐",
    lang: "en",
    tier: 3,
    interval: 480,
    aiTranslate: true,
    aiPriority: "low",
    active: true,
    description: "AI 最新论文预印本",
  },
  {
    id: "papers-with-code",
    name: "Papers with Code",
    url: "https://paperswithcode.com/rss",
    type: "rss",
    category: "ai",
    icon: "📄",
    lang: "en",
    tier: 3,
    interval: 480,
    aiTranslate: true,
    aiPriority: "low",
    active: true,
    description: "论文+代码实现，实用性强",
  },
  {
    id: "smol-ai",
    name: "Smol AI News",
    url: "https://buttondown.email/ainews/rss",
    type: "rss",
    category: "tech",
    icon: "🔥",
    lang: "en",
    tier: 3,
    interval: 1440,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  ...CRYPTO_SOURCES,
  ...STOCK_SOURCES,

  // ===== 新增国内可访问源 =====
  {
    id: "ce-cn",
    name: "中国经济网",
    url: "https://rss.ce.cn/",
    type: "rss",
    category: "cn",
    icon: "🏛",
    lang: "zh",
    tier: 2,
    interval: 60,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
    description: "官方经济新闻门户",
  },
  {
    id: "guancha",
    name: "观察者网",
    url: "https://www.guancha.cn/rss",
    type: "rss",
    category: "cn",
    icon: "📰",
    lang: "zh",
    tier: 2,
    interval: 60,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
    description: "时政与财经深度报道",
  },
];

export const ACTIVE_SOURCES = SOURCES.filter((s) => s.active);
export const TIER1_SOURCES = SOURCES.filter((s) => s.tier === 1 && s.active);
export const CATEGORIES = [
  { id: "ai", name: "AI·大模型", icon: "🤖" },
  { id: "tech", name: "科技", icon: "📱" },
  { id: "funding", name: "投融资", icon: "💰" },
  { id: "crypto", name: "币圈", icon: "₿" },
  { id: "us", name: "美股", icon: "🇺🇸" },
  { id: "cn", name: "A股", icon: "📈" },
];
