import type { SourceConfig } from "./types";

// ===== 股市 RSS 源 =====
const STOCK_SOURCES: SourceConfig[] = [
  // ===== A股 / 中文 =====
  {
    id: "xueqiu",
    name: "雪球",
    url: "https://xueqiu.com/rss",
    type: "rss",
    category: "cn",
    icon: "📊",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "cls-cn",
    name: "华尔街见闻",
    url: "https://wallstreetcn.com/feed",
    type: "rss",
    category: "cn",
    icon: "📈",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "caixin",
    name: "财新网",
    url: "https://www.caixin.com/rss/",
    type: "rss",
    category: "cn",
    icon: "📰",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "yicai",
    name: "第一财经",
    url: "https://www.yicai.com/feed",
    type: "rss",
    category: "cn",
    icon: "🏦",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "eastmoney",
    name: "东方财富",
    url: "https://finance.eastmoney.com/rss/",
    type: "rss",
    category: "cn",
    icon: "💹",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "fin-zh",
    name: "新浪财经",
    url: "https://rss.finance.sina.com.cn/rss/",
    type: "rss",
    category: "cn",
    icon: "📱",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  // ===== 美股 / 国际 =====
  {
    id: "ft-china",
    name: "FT中文网",
    url: "https://www.ftchinese.com/rss/feed",
    type: "rss",
    category: "us",
    icon: "📰",
    lang: "zh",
    tier: 1,
    interval: 30,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "reuters",
    name: "Reuters",
    url: "https://www.reutersagency.com/feed/",
    type: "rss",
    category: "us",
    icon: "🏛",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "investing",
    name: "Investing.com",
    url: "https://www.investing.com/rss/news.rss",
    type: "rss",
    category: "us",
    icon: "🌍",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "seekingalpha",
    name: "Seeking Alpha",
    url: "https://seekingalpha.com/feed.xml",
    type: "rss",
    category: "us",
    icon: "🏛",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/rssindex",
    type: "rss",
    category: "us",
    icon: "💹",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "wsj",
    name: "WSJ",
    url: "https://www.wsj.com/xml/rss/3_7085.xml",
    type: "rss",
    category: "us",
    icon: "📊",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "bloomberg",
    name: "Bloomberg",
    url: "https://feeds.bloomberg.com/markets/news.rss",
    type: "rss",
    category: "us",
    icon: "🏛",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "cnbc",
    name: "CNBC",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    type: "rss",
    category: "us",
    icon: "📺",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
];

// ===== 币圈 RSS 源 =====
const CRYPTO_SOURCES: SourceConfig[] = [
  {
    id: "coindesk",
    name: "CoinDesk",
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    type: "rss",
    category: "crypto",
    icon: "📰",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "cointelegraph",
    name: "Cointelegraph",
    url: "https://cointelegraph.com/rss",
    type: "rss",
    category: "crypto",
    icon: "⚡",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "theblock",
    name: "The Block",
    url: "https://www.theblock.co/rss",
    type: "rss",
    category: "crypto",
    icon: "📊",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "decrypt",
    name: "Decrypt",
    url: "https://decrypt.co/feed",
    type: "rss",
    category: "crypto",
    icon: "🔐",
    lang: "en",
    tier: 2,
    interval: 60,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "bitcoinmagazine",
    name: "Bitcoin Magazine",
    url: "https://bitcoinmagazine.com/rss",
    type: "rss",
    category: "crypto",
    icon: "₿",
    lang: "en",
    tier: 2,
    interval: 60,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "blockworks",
    name: "Blockworks",
    url: "https://blockworks.co/feed",
    type: "rss",
    category: "crypto",
    icon: "🏦",
    lang: "en",
    tier: 2,
    interval: 60,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "cryptoslate",
    name: "CryptoSlate",
    url: "https://cryptoslate.com/feed/",
    type: "rss",
    category: "crypto",
    icon: "📡",
    lang: "en",
    tier: 2,
    interval: 60,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
];

export const SOURCES: SourceConfig[] = [
  // ===== Tier 1 =====
  {
    id: "jiqizhixin",
    name: "机器之心",
    url: "https://www.jiqizhixin.com/rss",
    type: "rss",
    category: "ai",
    icon: "🤖",
    lang: "zh",
    tier: 1,
    interval: 15,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "qbitai",
    name: "量子位",
    url: "https://www.qbitai.com/feed",
    type: "rss",
    category: "ai",
    icon: "🔬",
    lang: "zh",
    tier: 1,
    interval: 15,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "mit-tech-review",
    name: "MIT Tech Review",
    url: "https://www.technologyreview.com/feed/",
    type: "rss",
    category: "ai",
    icon: "📐",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    url: "https://huggingface.co/blog/feed.xml",
    type: "rss",
    category: "ai",
    icon: "🤗",
    lang: "en",
    tier: 1,
    interval: 120,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "anthropic",
    name: "Anthropic",
    url: "https://anthropic.com/blog/rss",
    type: "rss",
    category: "ai",
    icon: "🤖",
    lang: "en",
    tier: 1,
    interval: 60,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "openai",
    name: "OpenAI",
    url: "https://openai.com/blog/rss",
    type: "rss",
    category: "ai",
    icon: "🧠",
    lang: "en",
    tier: 1,
    interval: 60,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "36kr",
    name: "36氪",
    url: "https://36kr.com/feed",
    type: "rss",
    category: "tech",
    icon: "📡",
    lang: "zh",
    tier: 1,
    interval: 15,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    type: "rss",
    category: "tech",
    icon: "🌐",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    url: "https://news.ycombinator.com/rss",
    type: "rss",
    category: "tech",
    icon: "💬",
    lang: "en",
    tier: 1,
    interval: 30,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "ruanyifeng",
    name: "阮一峰",
    url: "https://www.ruanyifeng.com/blog/atom.xml",
    type: "rss",
    category: "tech",
    icon: "📚",
    lang: "zh",
    tier: 1,
    interval: 1440,
    aiTranslate: false,
    aiPriority: "high",
    active: true,
  },
  {
    id: "simon-willison",
    name: "Simon Willison",
    url: "https://simonwillison.net/atom/everything/",
    type: "rss",
    category: "ai",
    icon: "✍️",
    lang: "en",
    tier: 1,
    interval: 120,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },

  // ===== Tier 2 =====
  {
    id: "ifanr",
    name: "爱范儿",
    url: "https://www.ifanr.com/feed",
    type: "rss",
    category: "tech",
    icon: "📱",
    lang: "zh",
    tier: 2,
    interval: 120,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "ithome",
    name: "IT之家",
    url: "https://www.ithome.com/rss",
    type: "rss",
    category: "tech",
    icon: "💻",
    lang: "zh",
    tier: 2,
    interval: 60,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "sspai",
    name: "少数派",
    url: "https://sspai.com/feed",
    type: "rss",
    category: "tech",
    icon: "✍️",
    lang: "zh",
    tier: 2,
    interval: 240,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "venturebeat",
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    type: "rss",
    category: "ai",
    icon: "📈",
    lang: "en",
    tier: 2,
    interval: 120,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "ars-technica",
    name: "Ars Technica AI",
    url: "https://arstechnica.com/ai/feed/",
    type: "rss",
    category: "tech",
    icon: "⚙️",
    lang: "en",
    tier: 2,
    interval: 240,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "deepmind",
    name: "DeepMind",
    url: "https://deepmind.google/blog/rss/",
    type: "rss",
    category: "ai",
    icon: "🧪",
    lang: "en",
    tier: 2,
    interval: 480,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "36kr-funding",
    name: "36氪创投",
    url: "https://36kr.com/motif/feed/117",
    type: "rss",
    category: "funding",
    icon: "💰",
    lang: "zh",
    tier: 2,
    interval: 120,
    aiTranslate: false,
    aiPriority: "normal",
    active: true,
  },
  {
    id: "crunchbase",
    name: "Crunchbase News",
    url: "http://news.crunchbase.com/feed/",
    type: "rss",
    category: "funding",
    icon: "💰",
    lang: "en",
    tier: 2,
    interval: 240,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  // ===== 新增推荐源 =====
  {
    id: "one-useful-thing",
    name: "One Useful Thing",
    url: "https://oneusefulthing.substack.com/feed",
    type: "rss",
    category: "ai",
    icon: "🎓",
    lang: "en",
    tier: 2,
    interval: 480,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "latent-space",
    name: "Latent Space",
    url: "https://www.latent.space/feed",
    type: "rss",
    category: "ai",
    icon: "🔧",
    lang: "en",
    tier: 2,
    interval: 480,
    aiTranslate: true,
    aiPriority: "high",
    active: true,
  },
  {
    id: "smol-ai",
    name: "Smol AI News",
    url: "https://buttondown.email/ainews/rss",
    type: "rss",
    category: "tech",
    icon: "🔥",
    lang: "en",
    tier: 3,
    interval: 1440,
    aiTranslate: true,
    aiPriority: "normal",
    active: true,
  },
  ...CRYPTO_SOURCES,
  ...STOCK_SOURCES,
];

export const ACTIVE_SOURCES = SOURCES.filter((s) => s.active);
export const TIER1_SOURCES = SOURCES.filter((s) => s.tier === 1 && s.active);
export const CATEGORIES = [
  { id: "ai", name: "AI·大模型", icon: "🤖" },
  { id: "tech", name: "科技", icon: "📱" },
  { id: "funding", name: "投融资", icon: "💰" },
  { id: "crypto", name: "币圈", icon: "₿" },
  { id: "us", name: "美股", icon: "🇺🇸" },
  { id: "cn", name: "A股", icon: "📈" },
];
